version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    initdb:
      image: postgres:latest
      command: /bin/bash -c "sleep 5 && psql -h db -U ${DB_USER} -d ${DB_DATABASE} -c 'CREATE TABLE IF NOT EXISTS task (id SERIAL PRIMARY KEY, title TEXT, description TEXT);'"
      depends_on:
        - db
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

volumes:
  pgdata:
